language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t antondeswardt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true antondeswardt/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-148576959747"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY




http://dockerreact-env.qfhgakqd7p.us-east-2.elasticbeanstalk.com/